import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import 'animate.css/animate.compat.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

const poppins = localFont({
  src: './fonts/poppins.ttf',
  variable: '--font-poppins',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  headernav,
  footer,
}: Readonly<{
  children: React.ReactNode;
  headernav: React.ReactNode;
  footer: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <main className="bg-gradient-to-br from-[#08b0c4] via-[#0898cf] from-[20%] to-[#0846dc] to-[110%]">
          {headernav}
          {children}
        </main>
        {footer}
      </body>
    </html>
  );
}
